---
- hosts: localhost
  become: true
  tasks:
        - name: install packages
          apt:
                state: latest
                name:
                      - vim
                      - vim-syntastic
                      - git
                      - git-lfs
                      - git-restore-mtime
                      - dnsutils
                      - rsnapshot
                      - whois
                      - sshfs
                      - nfs-common
                      - command-not-found

- hosts: localhost
  tasks:
        # https://www.freecodecamp.org/news/bashrc-customization-guide/
        - name: set bash env 1
          blockinfile:
            path: ~/.bashrc
            block: |
                export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
                gpgconf --launch gpg-agent

                HISTTIMEFORMAT="%F %T "
                alias cd..='cd ..'
                alias ..='cd ..;pwd'
                alias ...='cd ../..;pwd'
                alias ....='cd ../../..;pwd'

        - name: set bash env HISTSIZE
          lineinfile:
                dest: ~/.bashrc
                line: 'HISTSIZE=9000'
                regex: 'HISTSIZE='
        - name: set bash env HISTFILESIZE
          lineinfile:
                dest: ~/.bashrc
                line: 'HISTFILESIZE=9000'
                regex: 'HISTFILESIZE='
