---
- name: Install with root privileges
  hosts: localhost
  become: true
  tasks:
        - name: Install apt packages
          ansible.builtin.apt:
                state: present
                name:
                      - vim
                      - vim-syntastic
                      - git
                      - git-lfs
                      - git-restore-mtime
                      - dnsutils
                      - rsnapshot
                      - whois
                      - sshfs
                      # NFS client
                      - nfs-common
                      # bash helper
                      - command-not-found
                      - build-essential
                      - rsync
                      - python3
                      - python3-pip

        - name: Install pip packages
          ansible.builtin.pip:
                name:
                      - ansible
                      - ansible-lint
                      - virtualenv


        - name: Set HISTTIMEFORMAT globaly
          ansible.builtin.lineinfile:
                dest: /etc/profile.d/timestamp.sh
                line: 'HISTTIMEFORMAT="%Y%m%d %T "'
                regex: 'HIST'
                create: true
                mode: "a+rx"


- name: Install user preferences
  hosts: localhost
  tasks:
        # https://www.freecodecamp.org/news/bashrc-customization-guide/
        - name: Set bash env 1
          ansible.builtin.blockinfile:
                path: ~/.bashrc
                block: |
                  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
                  gpgconf --launch gpg-agent

                  HISTTIMEFORMAT="%F %T "
                  alias cd..='cd ..'
                  alias ..='cd ..;pwd'
                  alias ...='cd ../..;pwd'
                  alias ....='cd ../../..;pwd'

        - name: Set bash env HISTSIZE
          ansible.builtin.lineinfile:
                dest: ~/.bashrc
                line: 'HISTSIZE=9000'
                regex: 'HISTSIZE='
        - name: Set bash env HISTFILESIZE
          ansible.builtin.lineinfile:
                dest: ~/.bashrc
                line: 'HISTFILESIZE=9000'
                regex: 'HISTFILESIZE='


        - name: Set git_config name Andrii Kravchyna
          community.general.git_config:
                name: user.name
                scope: global
                value: Andrii Kravchyna
        - name: Set git_config email andreykp@gmail.com
          community.general.git_config:
                name: user.email
                scope: global
                value: andreykp@gmail.com

        - name: Set git_config core.editor vim
          community.general.git_config:
                name: core.editor
                scope: global
                value: vim
        # git config --global core.autocrlf input
        - name: Set git_config core.autocrlf input
          community.general.git_config:
                name: core.autocrlf
                scope: global
                value: input
